/** Figma MCP assets — node 134:72555 sublayers */

/** Demo 2 assets — rail icons are local (Figma MCP URLs expire after ~7 days) */

const RAIL = "/demo-2/rail"
const CHAT = "/demo-2/chat"
const TABS = "/demo-2/tabs"
const COMPANIES = "/demo-2/companies"
const HOME = "/demo-2/home"
const CLARIFICATION = "/demo-2/clarification"
const TOOLBAR = "/demo-2/toolbar"

export const DEMO2_ASSETS = {
  logo: `${RAIL}/logo.jpg`,
  railDivider: `${RAIL}/divider.svg`,
  railSearch: `${RAIL}/search.svg`,
  railProgress: `${RAIL}/progress.svg`,
  railHome: `${RAIL}/home.svg`,
  railMessages: `${RAIL}/messages.svg`,
  railTasks: `${RAIL}/tasks.svg`,
  railGlobalSearch: `${RAIL}/global-search.svg`,
  railFlash: `${RAIL}/flash.svg`,
  railFlow: `${RAIL}/flow.svg`,
  railDashboard: `${RAIL}/dashboard.svg`,
  railBuilding: `${RAIL}/building.svg`,
  railUsers: `${RAIL}/users.svg`,
  railMoney: `${RAIL}/money.svg`,
  railFolder: `${RAIL}/folder.svg`,
  railListMail: `${RAIL}/list-mail.svg`,
  railListSpirals: `${RAIL}/list-spirals.svg`,
  chatArrowRight: "https://www.figma.com/api/mcp/asset/5f926580-36da-45ad-b94c-d6bd6c759544",
  chatSend: "https://www.figma.com/api/mcp/asset/70d42fad-9e2b-45cb-a477-13aad8183251",
  chatImport: "https://www.figma.com/api/mcp/asset/e92b46cf-65f2-4622-ba51-8e20b3ddd101",
  chatCopy: "https://www.figma.com/api/mcp/asset/1371a6f5-7b41-42dd-8abc-f5b61521ce21",
  chatVolume: "https://www.figma.com/api/mcp/asset/c80b9e94-dc98-4454-8e2e-40f5dc4d9a3a",
  chatMore: `${CHAT}/more.svg`,
  chatClock: `${CHAT}/clock.svg`,
  chatSidebar: `${CHAT}/sidebar.svg`,
  chatAdd: `${CHAT}/add.svg`,
  chatMic: `${CHAT}/mic.svg`,
  chatSubmit: `${CHAT}/submit.svg`,
  cotSearching: `${CHAT}/cot-searching.svg`,
  tabSource1a: `${TABS}/source1-a.png`,
  tabSource1b: `${TABS}/source1-b.png`,
  tabSource1c: `${TABS}/source1-c.png`,
  tabSource2a: `${TABS}/source2-a.png`,
  tabSource2b: `${TABS}/source2-b.png`,
  tabSource2c: `${TABS}/source2-c.png`,
  tabWebSearch: `${TABS}/web-search.svg`,
  toolbarSearch: "https://www.figma.com/api/mcp/asset/d024c8f5-73d2-4340-b01b-d6a9925ef79e",
  toolbarSearchClear: `${TOOLBAR}/search-clear.svg`,
  toolbarFilter: "https://www.figma.com/api/mcp/asset/eb492961-6af7-4c97-a6f8-7b3d13593de1",
  toolbarPublicToggle: "https://www.figma.com/api/mcp/asset/2daea750-52e3-428f-bd4c-267f235e52a0",
  toolbarFindSimilars: "https://www.figma.com/api/mcp/asset/42aa4485-22f2-4b32-9427-a102b3c43c63",
  toolbarReview: "https://www.figma.com/api/mcp/asset/995f9d05-7798-46da-b7b9-8996acdfa18a",
  resultsAddToList: "/demo-2/results/add-to-list.svg",
  resultsNoMatchSearch: "/demo-2/results/no-match-search.svg",
  /** Figma 114:37524 */
  resultsAiSearch: "/demo-2/results/no-match-ai-search.svg",
  companyClearline: `${COMPANIES}/clearline.jpg`,
  companyRiot: `${COMPANIES}/riot.jpg`,
  companyVouch: `${COMPANIES}/vouch.jpg`,
  companyWefunder: `${COMPANIES}/wefunder.jpg`,
  companyMandel: `${COMPANIES}/mandel.jpg`,
  companyKeynua: `${COMPANIES}/keynua.jpg`,
  companyYesgraph: `${COMPANIES}/yesgraph.jpg`,
  companyPowerMatrix: `${COMPANIES}/powermatrix.jpg`,
  companyMentorcam: `${COMPANIES}/mentorcam.jpg`,
  companyPando: `${COMPANIES}/pando.jpg`,
  companyMtailor: `${COMPANIES}/mtailor.jpg`,
  companyPadlet: `${COMPANIES}/padlet.jpg`,
  companyMonte: `${COMPANIES}/monte.jpg`,
  companyPointone: `${COMPANIES}/pointone.jpg`,
  companyPromptloop: `${COMPANIES}/promptloop.jpg`,
  homeSettings: `${HOME}/settings.svg`,
  homeSidebar: `${HOME}/sidebar.svg`,
  homeOnboarding: `${HOME}/onboarding.svg`,
  homeYcChip: `${HOME}/yc-chip.jpg`,
  homeFilter: `${HOME}/filter.svg`,
  homeImprove: `${HOME}/improve.svg`,
  homeEqualizer: `${HOME}/equalizer.svg`,
  homeRunSearch: `${HOME}/run-search.svg`,
  homeSearchList: `${HOME}/search-list.svg`,
  homeAvatar: `${HOME}/avatar.jpg`,
  homeArrowDown: `${HOME}/arrow-down.svg`,
  homeCommand: `${HOME}/command.svg`,
  homeSort: `${HOME}/sort.svg`,
  homeSavedSearchClone: `${HOME}/saved-search-clone.svg`,
  homeSavedSearchRemove: `${HOME}/saved-search-remove.svg`,
  homePlusGreen: `${HOME}/plus-green.svg`,
  homeNewBadgeAddList: `${HOME}/new-badge-add-list.svg`,
  homeNewBadgeAddSequence: `${HOME}/new-badge-add-sequence.svg`,
  homeNewBadgeQuickPreview: `${HOME}/new-badge-quick-preview.svg`,
  homeFilterCompany: `${HOME}/filter-company.svg`,
  homeFilterSimilarity: `${HOME}/filter-similarity.svg`,
  homeFilterIndustry: `${HOME}/filter-industry.svg`,
  homeFilterFunding: `${HOME}/filter-funding.svg`,
  homeFilterTech: `${HOME}/filter-tech.svg`,
  homeFilterJobSignal: `${HOME}/filter-jobsignal.svg`,
  homeFilterContacts: `${HOME}/filter-contacts.svg`,
  homeFundingCalendar: `${HOME}/calendar-03.svg`,
  homeFundingSliderGrip: `${HOME}/slider-grip.svg`,
  clarificationSearch: `${CLARIFICATION}/search.svg`,
  clarificationSearchWhite: `${CLARIFICATION}/search-white.svg`,
  clarificationFilter: `${CLARIFICATION}/filter.svg`,
  clarificationTick: `${CLARIFICATION}/tick.svg`,
  clarificationTailLarge: `${CLARIFICATION}/tail-large.svg`,
  clarificationTailSmall: `${CLARIFICATION}/tail-small.svg`,
  clarificationUserAvatar: `${CLARIFICATION}/user-avatar.jpg`,
} as const

export const DEMO2_TOOLBAR_PILL =
  "group inline-flex h-8 shrink-0 cursor-pointer items-center gap-[6px] rounded-[10px] border border-solid border-[#f2f2f2] border-[0.5px] bg-white pl-3 pr-3 shadow-[0px_0px_1px_rgba(119,119,119,0.12)] transition-[background-color,border-color,box-shadow,color] duration-150 ease-out hover:border-[#ddd] hover:bg-[#fdfdfd] hover:shadow-[0px_0px_0.5px_rgba(119,119,119,0.12)] disabled:cursor-not-allowed disabled:hover:border-[#f2f2f2] disabled:hover:bg-white disabled:hover:shadow-[0px_0px_1px_rgba(119,119,119,0.12)]"
